### ISSUE TITLE
Rewrite this piece of shit

### ISSUE THREAD

**Issue by petterroea** [InfectedLan/InfectedInfo#2]
It was written in a haste a year ago, and is very hard to maintain, as @halvors has experienced. I will rewrite it closer to infected, in an attempt at making it more maintainable.

Apparently there are some bugs too.

**Comment by halvors** [comment]
This should be looked at before infected preparations.

**Comment by petterroea** [comment]
Yep. This is propabily my thursday job.

**Comment by petterroea** [comment]
kinda fixed
