### ISSUE TITLE
Fix slides.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedInfo#3]
Slides does not work. It is JavaScript related, cause it fetches the slides just fine from the API.

**Comment by petterroea** [comment]
Infoscreen will be rewritten

**Comment by petterroea** [comment]
Ish done

**Comment by petterroea** [comment]
But leaving this for next time

**Comment by halvors** [comment]
@petterroea Ok, make sure this is done before deadline this time :+1:

**Comment by petterroea** [comment]
IIRC i fixed it on friday before infected. @halvors , do you remember? I think i did.

**Comment by halvors** [comment]
Yeah i do. But i'm confused about the comment:

> Ish done

**Comment by petterroea** [comment]
Oh, that was from before the lan. Propabily done now.
